services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
    environment:
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
